// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadVHD(arg1, arg2) {
  return window['go']['main']['App']['DownloadVHD'](arg1, arg2);
}

export function GetAvailableServers() {
  return window['go']['main']['App']['GetAvailableServers']();
}

export function GetVHDListFromServer(arg1) {
  return window['go']['main']['App']['GetVHDListFromServer'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
