// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDrivers(arg1) {
  return window['go']['main']['App']['BackupDrivers'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DownloadVHD(arg1, arg2) {
  return window['go']['main']['App']['DownloadVHD'](arg1, arg2);
}

export function GetAvailableServers() {
  return window['go']['main']['App']['GetAvailableServers']();
}

export function GetSystemDrivers() {
  return window['go']['main']['App']['GetSystemDrivers']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetVHDListFromServer(arg1) {
  return window['go']['main']['App']['GetVHDListFromServer'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadBackupHistory() {
  return window['go']['main']['App']['LoadBackupHistory']();
}

export function RestoreDrivers(arg1) {
  return window['go']['main']['App']['RestoreDrivers'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}
