// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadVHD(arg1:number,arg2:string):Promise<Record<string, any>>;

export function GetAvailableServers():Promise<Array<any>>;

export function GetVHDListFromServer(arg1:number):Promise<Array<any>>;

export function Greet(arg1:string):Promise<string>;
