// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDrivers(arg1:string):Promise<Record<string, any>>;

export function DeleteBackup(arg1:any):Promise<Record<string, any>>;

export function DownloadVHD(arg1:any,arg2:string):Promise<Record<string, any>>;

export function GetAvailableServers():Promise<Array<any>>;

export function GetSystemDrivers():Promise<Array<any>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetVHDListFromServer(arg1:any):Promise<Array<any>>;

export function Greet(arg1:string):Promise<string>;

export function LoadBackupHistory():Promise<Array<any>>;

export function RestoreDrivers(arg1:string):Promise<Record<string, any>>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:any):Promise<string>;
